services:
  postgres:
    image: postgres:16-alpine
    container_name: etuys-belge-takip-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etuys_belge_takip

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
